version: "3.0"
services:
  chat-app:
    image: node:12.13.1-slim
    volumes: 
      - ./chat-app:/app
    working_dir: /app
    command: bash -c "yarn && yarn dev"
    ports: 
      - 3000:3000
    environment:
      - CHATKIT_INSTANCE_LOCATOR=${CHATKIT_INSTANCE_LOCATOR}
      - TOKEN_PROVIDER_URL=/auth/token
  auth-server:
    image: node:12.13.1-slim
    volumes: 
      - ./auth-server:/app
    working_dir: /app
    command: bash -c "yarn && yarn run start"
    ports: 
      - 3001:80
    environment:
      - CHATKIT_INSTANCE_LOCATOR=${CHATKIT_INSTANCE_LOCATOR}
      - CHATKIT_PRIVATE_KEY=${CHATKIT_PRIVATE_KEY}
      - CHATKIT_TEST_TOKEN_PROVIDER_ENDPOINT=${CHATKIT_TEST_TOKEN_PROVIDER_ENDPOINT}
